### PR TITLE
Opaque initialization of Some

### LINKED ISSUE #119: Is `PokeOption::build_in_place()` missing, or am I missing something?
Currently there seems to be only strongly typed ways to build `Option`s, which is fine for struct/enum fields, but less fine for building lists/maps containing `Option<T>`.

I would have expected one or more of the following:

1. A way to convert a `PokeOption` into an `Opaque<'mem>` (like `build_in_place()` for other types).
3. A way to initialize a `PokeOption` and get a `PokeUninit` into its `Some(...)`.
4. A way to push/insert into `PokeList` or `PokeMap` by way of "emplacing" `PokeUninit`s.

Or I could be totally wrong and completely missing something. Please advise. :-)

### PR DESCRIPTION
**Pull request by simonask**
Added `PokeOption::build_in_place()` and `PokeOption::replace_with_some_opaque()` (not sure about the naming).

Also added support for parsing `null` in the JSON parser.

Closes #119

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Looks good. Sorry for the churn, but facet-poke and facet-peek have been merged into facet-reflect, so you have a bunch of merging to do. Good luck. I can take it over if you want; just tell me, and I'll resolve the merge conflicts :)

**Comment by simonask** [comment]
@fasterthanlime No problem, it's to be expected at this stage! I'll get things ready to merge.

**Comment by fasterthanlime** [comment]
> I'll get things ready to merge.

See `CONTRIBUTING.md`, you can run `just` and `just miri` to have your own little CI-at-home.

File: facet-testhelpers/src/lib.rs [hunk 1]
```diff
@@ -35,6 +35,6 @@ pub fn setup() {
     #[cfg(not(miri))]
     color_backtrace::install();
     let logger = Box::new(SimpleLogger);
-    log::set_boxed_logger(logger).unwrap();
+    _ = log::set_boxed_logger(logger);
```
Comment (simonask) [inline facet-testhelpers/src/lib.rs:38]: Note: Doesn't really belong in this PR, but I had to add this to get tests to run.
